### ISSUE TITLE
Companion bug with epiphan pearl

### ISSUE THREAD

**Issue by kegeltje** [bitfocus/companion-module-epiphan-pearl#5] opened 2020-07-07 08:48 UTC
Hi there,

First of all, love the software!
I am kinda new to this, however i've come across a bug where I am unable to start/stop streaming & recording (see attached file)
Whenever i click the button to start the stream i get this error message. All I've done is added the Pearl button for streaming and put it on start and once i press the button i receive this error message and simultaniously lose connection with the Companion application. 
![Knipsel](https://user-images.githubusercontent.com/67950202/86750637-65fff500-c03e-11ea-9c92-7d63fa533c74.PNG)
.

starting a stream or recording manual on the device works fine and the channel swapping feature is working flawlessly aswell.

I also notice that sometimes whenever i try to add a 'key down/on actions' button and select one, it doesn't add it and it'll stay as is. 

edit: Im using version v2.0.0

Kind Regards,

Tom

**Comment by MarcHagen** [comment] 2020-07-07 17:52
Hi there!

First welcome to github and companion! You did the right thing, so all is good :)

Second, you add the pearl button for streaming. Did you use the preset for that?
And if possible could you share your current companion config?

**Comment by kegeltje** [comment] 2020-07-08 07:57
Hi Marc,

Yes I have the Pearl connected. After trying to add it manually which didn't seem to work, i tried using the preset for streaming and that seemed to work without a problem! :) I can press the stream button and the stream goes on and off without any problems!

Which brings me to a new issue unfortunately.. since this now worked for streaming, i tried it for recording too. 
But when i drag the preset inside the button panel, nothing is being added (see picture)

![Knipse2l](https://user-images.githubusercontent.com/67950202/86891854-c014bf00-c0ff-11ea-94a8-f9817c7f7407.PNG)

I also notice when i try to add the "Pearl: start/stop recording" manually, nothing happens either. As if nothing is assigned to this function. It just appears for a split second and then its back to the original state as shown in picture.

I tried restarting the program and the Pearl aswell but to no avail.

Also, much appreciated the quick response from before!!

Also I added a screenshot of the devices I am using at the moment and also exported the page as shown above along with the recording issue I'm now facing. Since I'm relatively new in this, I'm unsure if you need more info from me and if you do, which info it is you need. Feel free to ask me anything

Many thanks in advance!


[DESKTOP-3A96AI6_page 3_20200708-0954.zip](https://github.com/bitfocus/companion-module-epiphan-pearl/files/4889235/DESKTOP-3A96AI6_page.3_20200708-0954.zip)


![Knipsel3](https://user-images.githubusercontent.com/67950202/86892378-75e00d80-c100-11ea-914a-8789cca8e9cb.PNG)

**Comment by MarcHagen** [comment] 2020-07-08 21:57
Just a quick update on this, 

This information is all i need for now. I see the bug what you described, but im not convinced that is the module that is at fault but the companion gui itself. 
Still i'm looking if we / i can fix it :)

**Comment by PhotoJoseph** [comment] 2021-01-30 01:13
Hi @MarcHagen, I'm new here as well and am running into what I think is the same issue that @kegeltje had. 

I'm using a Pearl-2.

I first tried adding record (manually adding the action, not using the presets), and the UI appeared in the button settings to choose which channel to record as expected, but it wouldn't start recording. I then tested a button with a layout change, and that did work, although it took about 8 seconds for the change to show up on the Pearl (at least in the Pearl web UI; I was not looking at the hardware itself). Since I couldn't get Record to work for that channel, I tried setting up a new recorder as a main Recorder, not a unique channel recorder, and at that point, everything broke. Now when I add a new action, nothing shows up in the action list at all, just like in the screenshots above. 

Also if I try by adding presets, even though I have presets to add, when I do, they're all blank. 

In continuing to test it, I tried adding a command (change channel) to KEY UP instead of KEY DOWN, and it added it! And it actually worked almost instantly when I pressed it. I then added a Record function… and it all broke again. And now once again I can't add a command to either DOWN or UP. 

Finally, I deleted the Pearl from the Connections, re-added it, and I was able to once again add a single action (change layout), test it (it worked but took about 8 seconds again), and then when I added another one, the first one disappeared and I can't add any more.

Happy to test new builds!
Thanks
-Joseph

**Comment by MarcHagen** [comment] 2021-01-30 19:34
Hi @PhotoJoseph ,

First welcome :)

It's a shame to hear you have issues with companion and the Pearl.
I will look into this, at the moment i'm not really able to test with a Pearl unit (as i personally don't have one and well covid...) but i will try to see if i can reproduce the issue.

**Comment by PhotoJoseph** [comment] 2021-01-31 06:03
Thanks @MarcHagen. If there's a way I can help (i.e. give you remote access to mine for testing), let me know. 

In the meantime, maybe you could offer a hint, if you know the answer? I have the URL mentioned previously that will trigger the Pearl from a browser, but I can't get that to work via the http instance in Companion. I entered the Pearl’s IP in the instance setup, and the rest of the URL in the GET command, but it doesn’t do anything on the Pearl. I’ve tried the other commands as well (POST and PUT), and a variety of other URL combos, but haven’t been successful. This would at least hold me over for the most immediate need until your tool was up and running again. If you have any ideas, I’m all ears!!

Thanks,
-Joseph

**Comment by MarcHagen** [comment] 2021-02-07 16:46
Hi @PhotoJoseph,

So apparently my previous comment has not been posted...
If have changed something in the code, which gave me also the error. And this has been merged (now 6 days ago) into companion.
Could you please test the latest build (https://bitfocus.io/companion/download/builds/) and check if you still have issues?

**Comment by PhotoJoseph** [comment] 2021-02-07 18:01
Hey @MarcHagen I actually did already test that, as I saw that there were some Pearl changes, but it didn't fix it. I didn't test extensively so I can't say if anything changed, but it definitely didn't fix the record start/stop. I can test more extensively tomorrow if you need more info.

**Comment by MarcHagen** [comment] 2021-02-07 18:30
@PhotoJoseph
Thats a shame, if you could do me a favor and open de pearl GUI (not the admin interface but the fancy one) and save the whole webpage (including the assets js/images) and zip attach that here.

**Comment by PhotoJoseph** [comment] 2021-02-07 20:25
@MarcHagen Sure thing, but I'm not quite sure how you mean for me to save the page? I did a "save as" in Safari and saved it as both a web archive and a page source, but I don't think that's what you mean. It's attached though just in case it is! If not, please advise.
[Pearl2.zip](https://github.com/bitfocus/companion-module-epiphan-pearl/files/5939885/Pearl2.zip)

![IMG_0339](https://user-images.githubusercontent.com/78106443/107158515-8929b480-693f-11eb-98ba-92df341563be.jpeg)

**Comment by MarcHagen** [comment] 2021-02-07 20:37
Thats good, didn't know you used a Mac :P Doens't matter i can unpack the webarchive and it contains what i need :)

**Comment by MarcHagen** [comment] 2021-02-07 21:23
@PhotoJoseph Oke so i'm not really getting why you're device isn't working :/
 Code seems oke, so to further help you it's maybe best to do this more "live" then though github comments :)
 Are you by any chance on the Bitfocus Slack? If not please create a account on [Bitfocus.io Slack](https://join.slack.com/t/bitfocusio/shared_invite/enQtODk4NTYzNTkzMjU1LTMzZDY1Njc2MmE3MzVlNmJhMTBkMzFjNTQ2NzZlYzQyZWIzZTJkZWIyNmJlY2U0NzM1NGEzNzNlZWY3OWJlNGE) .
You can DM me there: mhagen 

Then maybe if possible i can interact live with the pearl to test it and maybe figure out why it's not working properly.
If you're okay with this, just hit me up on Slack :)  Doesn't have to be now, we can arrange a date/time.

**Comment by PhotoJoseph** [comment] 2021-02-07 22:55
Yep, I'll do that. Thanks!

**Closed** 2021-02-12 21:12 UTC
Labels: bug

**Comment by MarcHagen** [comment] 2021-02-12 21:20
While this is closed, it's not yet in the core updated.
Will give a update when this is done :)

**Comment by MarcHagen** [comment] 2021-02-15 17:56
So it's 1/2 days. Which gave the builder time to make a nightly/new experimental build.
You can find the builds here: https://bitfocus.io/companion/download/builds/

Please let me know if you have any more issues.
Open this issue if you still have problems related to this.
Open a new issue for features or other types of bugs

**Comment by ethan-tripp** [comment] 2021-03-05 17:02
Hello, I'm also having some issues with the Epiphan Pearl module in latest build. Commands to launch channel records are broken, and feedback for channel records seems to work off and on. Can answer any followup questions and test on my end!

**Comment by MarcHagen** [comment] 2021-03-06 21:03
@ethan-tripp Did you use the latest build (experimental build?) or just the normal latest build before you reverted back to 2.2.0.

**Comment by ethan-tripp** [comment] 2021-03-06 21:13
@MarcHagen I used the latest experimental build available as of yesterday afternoon when I commented.
